### ISSUE TITLE
v0.2+ has issues with alias bash completion

### ISSUE THREAD

**Issue by christianh814** [akuity/argo-cd-learning-assets#7]
Looks like moving things out of `/etc/bash.bashrc` broke the `k` alias bash completion

![image](https://github.com/akuity/argo-cd-learning-assets/assets/10502863/e06b2c8a-e5a3-403a-81c4-7d224fe3047d)

**Comment by jessesuen** [comment]
Fixed in https://github.com/akuity/argo-cd-learning-assets/pull/8
